name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-for-release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Release Tag
        run: exit ${{github.ref_type != 'tag'}}
#      - name: Release tag exists
#        if: github.ref_type == 'tag'
#        run: exit 0  
  next-job:
    needs: check-for-release-tag
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo Hello World
    
