name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-for-release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Release tag is missing
        if: github.ref_type != 'tag'
        run: echo "Hallo"
      - name: Release tag exists
        if: github.ref_type == 'tag'
        run: echo "Hallo"
