name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
#  if-else:
#    runs-on: ubuntu-latest
#    if: github.ref_type == 'tag'
#    steps:
#      - name: Release tag is missing
#      run: echo "Hallo"
  job_name:
    runs-on: windows-latest
    if: 5 == 5
    steps:
      - name: condition 1
#        if: "contains(github.event.head_commit.message, 'CONDITION 1 MSG')"
        run: echo "Hallo Welt"
